name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - "2283:2283"
    depends_on:
      - redis
      - database
    # GPU reservation for video transcoding
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    restart: 'unless-stopped'
    networks:
      - default
      - crt_service_intranet # Caddy accessibility

  immich-machine-learning:
    container_name: immich_machine_learning
    # IMPORTANT: Use the -cuda tag for ML acceleration
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}-cuda
    environment:
      - IMMICH_MACHINE_LEARNING_ACCELERATION=cuda
    volumes:
      - ${ML_CACHE_LOCATION}:/cache
    env_file:
      - .env
    # GPU reservation for Facial Recognition and Smart Search
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    restart: 'unless-stopped'

  redis:
    container_name: immich_redis
    image: docker.io/valkey/valkey:8-bookworm
    restart: 'unless-stopped'

  database:
    container_name: immich_database
    image: ghcr.io/immich-app/postgres:14-vectorchord0.4.3-pgvectors0.2.0@sha256:bcf63357191b76a916ae5eb93464d65c07511da41e3bf7a8416db519b40b1c23
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      DB_STORAGE_TYPE: SSD
    volumes:
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' || exit 1;
    restart: 'unless-stopped'

networks:
  crt_service_intranet:
    external: true
